### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by shubhamrk2** [itsPiyushMaheshwari/SDV#10]
@itsPiyushMaheshwari can you please help me in SDV project of yours.

**Comment by itsPiyushMaheshwari** [comment]
I haven't maintaining it since more than an year, if you have specific
question let me know.

**Comment by akirakurasova** [comment]
@itsPiyushMaheshwari hi bro i tried to run your project but i can't register through metamask, do you know what is the issue.

**Comment by itsPiyushMaheshwari** [comment]
May be packages used got deprecated now.

**Comment by shubhamrk2** [comment]
@itsPiyushMaheshwari could you please help us with the new solidity code, there might be some changes, and definitely you know. It will be a great help.
thankyou

**Comment by itsPiyushMaheshwari** [comment]
Sorry but I have created it past back you need to check, but as far as I remember I have pushed latest commit for smart contract. Please check at your end.
